# Generated by Django 2.2 on 2019-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190417_0607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='My_Card',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
